name: NicolasMorinPhotography
favicon: null
layout_spectrum: 0.93303
typography_spectrum: 0.00121
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6d9e2'
    - '#b5b7c3'
    - '#060606'
    - '#8e919a'
    - '#4e4f53'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
